/* jshint strict: false */
module.exports = function( grunt ){

	grunt.initConfig({
		// uglify: {
		//	options: {
		//		mangle: true,
		//		compress: true,
		//		banner: "/* Datasoft Engineering 2016 - Author: Reedyseth @since 21-Apr-2016 - Generated by GruntJS and UglifyJS */\n"
		//	},
		//	bom: {
		//		src: "O:/source/js/bom_tool/dish_bom.js",
		//		dest: "O:/source/js/bom_tool/min/dish_bom.min.js"
		//	}
		// },
		watch: {
			options: {
				spawn: false
			},
			scripts: {
				files: [ "src/pug/**/*.jade" ],
				tasks: [ "pug" ]
			}
		},
		pug: {
			compile: {
				options: {
					pretty: true
				},
				files: {
					'src/index.html': 'src/pug/index.jade'
				}
			}
		}
	});

	grunt.loadNpmTasks( 'grunt-contrib-pug' );
	// grunt.loadNpmTasks( 'grunt-contrib-uglify' );
	grunt.loadNpmTasks( 'grunt-contrib-watch' );
};